language: go
go:
  - 1.13.4

env:
  - DOCKER_TAG_LATEST=true DOCKER_REGISTRY=registry.hub.docker.com DOCKER_REGISTRY_ORG=daocasino

services:
  - docker

notifications:
  email: false

jobs:
  include:
    - stage: lint & test
      if: (branch IN (master,develop)) AND (type IN (push, pull_request))
      script:
        - make test
    - stage: build
      if: (branch IN (master,develop)) AND (type IN (push, pull_request))
      script:
        - make build
    - stage: package
      if: (branch IN (master,develop)) AND (type IN (push, pull_request))
      script:
        - make package
        - make publish
    - stage: promote
      if: tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+
      script:
        - make promote

after_success:
  - bash <(curl -s https://codecov.io/bash)
