language: go
go:
  - 1.13.4
services:
  - docker
notifications:
  email: false
env:
  - DOCKER_TAG_LATEST=true
  - DOCKER_REGISTRY=test
script:
  - make build
  - make test
#  - make package
#  - make publish
after_success:
  - bash <(curl -s https://codecov.io/bash)
