database:
  url: postgres://test:test@localhost/test
  filter:
    name:
    account:
server:
  addr: :8888
session:
  writeWait: 10s
  pongWait: 60s
  maxMessageSize: 4096
upgrader:
  readBufferSize: 1024
  writeBufferSize: 1024
abi:
  main: ../contract.abi
  events:
    0: ../event.abi
    1: ../event.abi