version: '3'
services:
  monitor:
    container_name: action-monitor
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./configs:/root/configs
    command: -config configs/config.docker.yml
