version: '3'
services:
  database:
    image: postgres:11.1-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - eos-network
  history-tools:
    container_name: eosnode-history-tools
    image: daocasino/eosnode-history-tools:latest
    depends_on:
      - database
    command: /root/history-tools/build/fill-pg --fpg-drop --fpg-create --fill-connect-to 192.168.1.3:8080
    environment:
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
      PGHOST: database
    networks:
      - eos-network
networks:
  eos-network:
