database:
  url: postgres://test:test@localhost/test
  filter:
    name:
    account:
server:
  addr: :8888
session:
  writeWait: 10s
  pongWait: 60s
  maxEventsInMessage: 50
upgrader:
  readBufferSize: 1024
  writeBufferSize: 1024
abi:
  main: /app/abi/contract.abi
  events:
    0: /app/abi/events/game_started.abi
    1: /app/abi/events/action_request.abi
    2: /app/abi/events/signidice_part_1_request.abi
    3: /app/abi/events/signidice_part_2_request.abi
    4: /app/abi/events/game_finished.abi
    5: /app/abi/events/game_failed.abi
    6: /app/abi/events/game_message.abi
eventExpires: 1 hour
sharedDatabase:
  url: postgres://test:test@localhost/monitor
