database:
  url: postgres://test:test@192.168.1.3:5431/test
  filter:
    name: send
    account: tevents
server:
  addr: 0.0.0.0:8888
session:
  writeWait: 10s
  pongWait: 60s
  maxEventsInMessage: 50
upgrader:
  readBufferSize: 1024
  writeBufferSize: 1024
abi:
  main: configs/abi/contract.abi
  events:
    0: configs/abi/event_0.abi
eventExpires: 2 day
