database:
  url: postgres://test:test@localhost/test
  filter:
    name:
    account:
server:
  addr: :8888
session:
  writeWait: 10s
  pongWait: 60s
  maxEventsInMessage: 50
upgrader:
  readBufferSize: 1024
  writeBufferSize: 1024
abi:
  main: /app/abi/contract.abi
  events:
    0: /app/abi/event.abi
    1: /app/abi/event.abi
eventExpires: 1 hour
sharedDatabase: postgres://test:test@localhost/monitor