service:
  addr: :8888 # host:port

session:
  writeWait: 10s   # Time allowed to write a message to the client.
  pongWait: 60s # Time allowed to read the next pong message from the client.
  maxMessageSize: 4096 # Maximum message size allowed from client.

upgrader: # websocket upgrader
  readBufferSize: 1024
  writeBufferSize: 1024